modLoader = "javafml"
loaderVersion = "[4,)"
license = "CC0-1.0"

[[mods]]
modId = "tiertagger"
version = "${version}"
displayName = "Tier Tagger"
authors = "Blue_Bed, MrDrak"
description = '''Official Tier Tagger mod for tiertests.com'''
logoFile = "assets/tiertagger/icon.png"

[[mixins]]
config = "tiertagger-common.mixins.json"

[[mixins]]
config = "tiertagger-neoforge.mixins.json"

[[dependencies.tiertagger]]
modId = "neoforge"
type = "required"
versionRange = "[21.9,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.tiertagger]]
modId = "minecraft"
type = "required"
versionRange = "[1.21.9,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.tiertagger]]
modId = "architectury"
type = "required"
versionRange = "[19.0.0,)"
ordering = "AFTER"
side = "BOTH"
